// Public database entry point for microJBase (v0.1 plus the v0.2 schema
// catalogue reader and schema snapshot reader).
//
// Exports the pool and transaction helpers. Repository adapters and the
// migration runner live in sibling files and are imported by their callers.

export {
  createPool,
  translatePoolError,
  type Pool,
  type PoolConfig,
} from "./pool.js"
export {
  createTransactionRunner,
  translateTransactionError,
  type TransactionContext,
  type TransactionOptions,
  type TransactionRunner,
} from "./transaction.js"
export {
  checkRuntimeRoleSafety,
  checkTableOwnershipAndRls,
  checkRuntimeTablePrivileges,
  checkApplicablePolicies,
  type RuntimeRoleSafety,
  type TableOwnershipCheck,
  type TablePrivilegeCheck,
  type PolicyCheck,
  type RuntimeTableSafety,
} from "./role-safety.js"
export { createAuthRepository } from "./auth-repository.js"
export {
  createPostgresDataRepository,
  translateDataError,
  type PostgresDataRepositoryDependencies,
} from "./data-repository.js"
export {
  buildTableRegistry,
  buildTableRegistryFromEnv,
  quoteIdentifier,
  quoteTableIdentifier,
  type ExposedTableMapping,
  type TableRegistryConfig,
  type RegistryBuildDependencies,
} from "./table-registry.js"
export {
  createSchemaCatalogueReader,
  readSchemaCatalogue,
  type SchemaCatalogueDependencies,
} from "./schema-catalogue.js"
export {
  MIGRATION_HISTORY_SQL,
  classifySchemaObject,
  createSchemaSnapshot,
  createSchemaSnapshotReader,
  mapMigrationHistory,
  readMigrationHistory,
  readSchemaSnapshot,
  type MigrationHistoryRow,
  type SchemaSnapshotDependencies,
  type SchemaSnapshotExposedTable,
  type SchemaSnapshotInput,
} from "./schema-snapshot.js"
export {
  SCHEMA_ADMIN_MAX_CONNECTIONS,
  assertSchemaAdminSessionDistinct,
  checkSchemaAdminRoleSafety,
  createSchemaAdminPool,
  type SchemaAdminPoolConfig,
  type SchemaAdminRoleSafety,
} from "./schema-admin-pool.js"
export {
  checkSchemaOperationLogWriteAccess,
  computeActorFingerprint,
  computeOperationChecksum,
  createSchemaOperationLog,
  type BeginOperationInput,
  type ListOperationsInput,
  type SchemaOperationBeginOutcome,
  type SchemaOperationLog,
  type SchemaOperationLogDependencies,
  type SchemaOperationRecord,
  type SchemaOperationStatus,
} from "./schema-operation-log.js"
export {
  MIGRATION_LOCK_KEY_FOR_DISTINCTION,
  SCHEMA_DDL_LOCK_KEY,
  SAFE_TYPE_CONVERSIONS,
  assertDdlIdentifier,
  compileAddColumn,
  compileChangeColumnType,
  compileCreateTable,
  compileDropColumn,
  compileDropColumnDefault,
  compileDropNotNull,
  compileDropTable,
  compileRenameColumn,
  compileRenameTable,
  compileSetColumnDefault,
  compileSetNotNull,
  createSchemaDdlExecutor,
  describePlan,
  translateDdlError,
  type AddColumnSpec,
  type ChangeColumnTypeSpec,
  type ColumnDefaultSpec,
  type ColumnTargetSpec,
  type CreateTableSpec,
  type DdlColumnDefault,
  type DdlColumnSpec,
  type DdlColumnType,
  type DdlPlan,
  type DropColumnSpec,
  type DropTableSpec,
  type ExecuteOptions,
  type ExecuteOutcome,
  type RenameColumnSpec,
  type RenameTableSpec,
  type SchemaDdlExecutor,
  type SchemaDdlExecutorDependencies,
  type SchemaOperationLogQuery,
} from "./schema-ddl.js"
export {
  createSchemaMutationService,
  mapCatalogueType,
  type AddColumnCommand,
  type ChangeColumnTypeCommand,
  type ColumnCommandBase,
  type CreateTableCommand,
  type DropColumnCommand,
  type DropTableCommand,
  type ManagedColumnSpec,
  type MutationCommandBase,
  type RenameColumnCommand,
  type RenameTableCommand,
  type SchemaMutationService,
  type SchemaMutationServiceDependencies,
  type SetColumnDefaultCommand,
} from "./schema-mutations.js"
export {
  buildImportPayload,
  findExposureByAlias,
  findExposureByTarget,
  importInitialExposure,
  readExposureRegistryState,
  type ExposureRegistryEntry,
  type ExposureRegistryRow,
  type ExposureRegistryState,
} from "./exposure-registry.js"
export {
  createSwappableTableRegistry,
  type SwappableTableRegistry,
} from "./table-registry.js"
export {
  compileAddForeignKey,
  compileAddUniqueConstraint,
  compileAssertExposurePrerequisites,
  compileAssertNotExposed,
  compileCreateIndex,
  compileCreateOwnershipPolicy,
  compileDisableRowSecurity,
  compileOwnershipComparison,
  compileDropConstraint,
  compileDropIndex,
  compileDropOwnershipPolicy,
  compileEnableRowSecurity,
  compileGrantRuntimePrivileges,
  compileMarkExposed,
  compileMarkUnexposed,
  compileRevokeRuntimePrivileges,
  compileVerifyRuntimePrivilegesRevoked,
  deterministicObjectName,
  EXPOSED_MUTATION_GUARD_SQLSTATE,
  EXPOSURE_GUARD_SQLSTATE,
  ownershipPolicyName,
  ownershipPolicyTemplateShape,
  type AddForeignKeySpec,
  type AddUniqueConstraintSpec,
  type ColumnPrivilegeGrant,
  type CreateIndexSpec,
  type DropConstraintSpec,
  type DropIndexSpec,
  type DropOwnershipPolicySpec,
  type ExposurePrerequisiteSpec,
  type ForeignKeyAction,
  type ForeignKeyReferenceSpec,
  type GrantRuntimePrivilegesSpec,
  type MarkExposedSpec,
  type MarkUnexposedSpec,
  type OwnershipPolicySpec,
  type OwnershipPolicyTemplate,
  type RevokeRuntimePrivilegesSpec,
  type RowSecurityTargetSpec,
} from "./schema-ddl.js"
export {
  createSchemaConstraintService,
  type AddForeignKeyCommand,
  type AddUniqueConstraintCommand,
  type ConstraintCommandBase,
  type CreateIndexCommand,
  type DropConstraintCommand,
  type DropIndexCommand,
  type ForeignKeyReferenceCommand,
  type SchemaConstraintService,
  type SchemaConstraintServiceDependencies,
} from "./schema-constraints.js"
export {
  checkExposureRegistryWriteAccess,
  createSchemaExposureService,
  verifyExposureCandidate,
  type ExposeTableCommand,
  type ExposureCommandBase,
  type ExposureVerification,
  type OwnershipComparisonProbe,
  type RenderedOwnershipComparison,
  type RenderedPolicyExpressions,
  type SchemaExposureService,
  type SchemaExposureServiceDependencies,
  type UnexposeTableCommand,
} from "./schema-exposure.js"
export {
  createSchemaPolicyService,
  createSchemaRlsService,
  type CreateOwnershipPolicyCommand,
  type DisableRowSecurityCommand,
  type EnableRowSecurityCommand,
  type RemoveOwnershipPolicyCommand,
  type RlsCommandBase,
  type SchemaPolicyService,
  type SchemaPolicyServiceDependencies,
  type SchemaRlsService,
  type SchemaRlsServiceDependencies,
} from "./schema-rls.js"
export {
  type ColumnMetadata,
  type VerifiedTableMetadata,
} from "./table-types.js"
